version: "3"

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
    - "1234:1234"
    command: server --port=1234
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    command: client --host=server:1234
    depends_on:
      - server
