version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
    - "1234:1234"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - SERVER_HOST=server:1234
